spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/preschool
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082

fcm:
  certification: serviceAccountKey.json

file:
  dir: D:/download/greengram4/